### ISSUE TITLE
BrightFutures 3.0.0 depend on Result 0.6.0-beta.4

### ISSUE THREAD

**Issue by jhntrifork** [Thomvis/BrightFutures#92] opened 2015-11-03 20:34 UTC
When I try to upload my app to iTunesConnect I get an error:
The value for key CFBundleShortVersionString '0.6.0-beta.4' in the Info.plist file must be a period-separated list of at most three non-negative integers.

I fixed it by manually editing the plist file in the Result pod, but a real fix is welcome :-)

Thank you for a great framework!

Cheers,
Jon

**Comment by Thomvis** [comment] 2015-11-03 21:40
Sorry to hear you encountered issues. Happy to hear you worked it out.

For further reference, I think this issue is a duplicate of https://github.com/Thomvis/BrightFutures/issues/88 and can be solved with a fix that is linked to from that issue.

**Closed by Thomvis** 2015-11-03 21:40 UTC
